"""empty message

Revision ID: 04abfe79ee9a
Revises: bc7b1dd477a1
Create Date: 2021-08-24 20:18:15.407778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04abfe79ee9a'
down_revision = 'bc7b1dd477a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messageboard',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('mdatetime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messageboard')
    # ### end Alembic commands ###
