"""empty message

Revision ID: bc7b1dd477a1
Revises: d7ad318a76d9
Create Date: 2021-08-24 19:22:40.497985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc7b1dd477a1'
down_revision = 'd7ad318a76d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aboutme', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'aboutme', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aboutme', type_='foreignkey')
    op.drop_column('aboutme', 'user_id')
    # ### end Alembic commands ###
